### ISSUE TITLE
a = (a+a)[:] leading to TypeError: Cannot read properties of null (reading 'setLine')

### ISSUE THREAD

**Issue by ide1ta** [ayecue/greybel-vs#255] opened 2024-10-27 16:46 UTC
greybel-vs, probably greybel-language server bug?

Pasting this code: a = (a+a)[:]
Leads to these errors, and breaks hovering:

TypeError: Cannot read properties of null (reading 'setLine')
    at pb.resolveSliceExpression (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:110:3034)
    at pb.resolveType (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:110:4502)
    at pb.analyze (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:110:10393)
    at t.analyze (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:110:13640)
    at bb.analyze (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:110:18067)
    at t_.create (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:210:26732)
    at t_.refresh (c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:210:26523)
    at c:\Users\1\.vscode\extensions\ayecue.greybel-vs-2.5.1\node_modules\greybel-languageserver\index.js:210:26350
(when trying to hover)[Error - 7:43:55 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of null (reading 'setLine')
  Code: -32603 
 (when trying to use auto-completion)[Error - 7:47:31 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read properties of undefined (reading 'aggregator')
  Code: -32603 

Image: https://imgur.com/6MN3dGC

**Comment by ayecue** [comment] 2024-10-27 17:00
Yes it is indeed related to the `greybel-languageserver` to be more precise it's related to the `miniscript-type-analyzer`. I'll give an update once the issue is fixed.

**Comment by ayecue** [comment] 2024-10-27 19:57
Alright I just released version `2.5.2`. Your issue should be fixed now. In case you still experience issues feel free to reopen this ticket. Thanks for reporting.

**Closed by ayecue** 2024-10-27 19:57 UTC
Labels: bug
