### ISSUE TITLE
Missing Go to Definition

### ISSUE THREAD

**Issue by linuxgruven** [ayecue/greybel-vs#240] opened 2024-08-18 17:12 UTC
Not showing 'Go to Definition' in the context menu. Was there a resent change?

**Comment by ayecue** [comment] 2024-08-18 17:53
Hey, with version 2.4.9 the extension is now using a language server not sure if that might be the cause for you.
<img width="422" alt="Screenshot 2024-08-18 at 19 51 56" src="https://github.com/user-attachments/assets/937dbe98-266f-496e-90c3-532038b418e4">
Maybe first thing to try out is to restart VSCode not sure if that might be the reason.

I've tested on Mac and Windows though and for me it's showing the "Go to Definition" fine. Could you please share an example file in which it prior to the change worked? You can do that by just installing version 2.4.8.
<img width="409" alt="Screenshot 2024-08-18 at 19 51 15" src="https://github.com/user-attachments/assets/da2a8e4f-a150-458f-beca-3ee0dda4ab95">

**Comment by linuxgruven** [comment] 2024-08-18 23:26
yeah it works in 2.4.8
here is what 2.4.9 and 2.4.10 shows -
![2 4 10](https://github.com/user-attachments/assets/bec3e0aa-ea75-4065-8c89-6754f3cde558)
2.4.8 - 
![2 4 8](https://github.com/user-attachments/assets/11d9a130-b22d-417d-9a41-852d9e062b34)

**Comment by linuxgruven** [comment] 2024-08-18 23:30
Using -
![neo](https://github.com/user-attachments/assets/2306dd14-112a-4c3b-924b-a2e13b6224db)

**Comment by ayecue** [comment] 2024-08-18 23:38
Interesting, but things such as hover tooltips still show?

Could you maybe add example code which replicates the issue? Don't need the whole source code just the parts that lead to this issue.

**Comment by linuxgruven** [comment] 2024-08-18 23:39
Yes all that works perfectly...just noticed peek not showing either...I don't use it much

**Comment by linuxgruven** [comment] 2024-08-18 23:41
any function call would not show and did not have hover tooltips

**Comment by linuxgruven** [comment] 2024-08-18 23:41
no hover tips for built in functions as well

**Comment by linuxgruven** [comment] 2024-08-18 23:42
sorry on versions 2.4.9 and 10 not showing 8 works fine

**Comment by ayecue** [comment] 2024-08-18 23:44
Sounds like the language server is not able to read the files. Are you using workspaces?

I'll probably need to setup a VM with the same OS. Not sure if it's maybe permissions.

**Comment by linuxgruven** [comment] 2024-08-18 23:46
Not sure I just use it for grey hack I have seen workspaces but never messed with em

**Comment by linuxgruven** [comment] 2024-08-18 23:48
I do have folders but my source code is in root folder

**Comment by linuxgruven** [comment] 2024-08-18 23:51
![rt](https://github.com/user-attachments/assets/9f693782-f95b-464b-89eb-807ddca025ec)

**Comment by ayecue** [comment] 2024-08-19 00:14
One more question are there any errors showing in the console when clicking "Toggle Developer Tools"?
<img width="691" alt="Screenshot 2024-08-19 at 02 13 33" src="https://github.com/user-attachments/assets/361dbaae-998c-47da-b530-9f865c9e079f">

**Comment by linuxgruven** [comment] 2024-08-19 00:22
![error](https://github.com/user-attachments/assets/663803aa-36fa-4d52-b6c6-8eb960df14fb)

**Comment by linuxgruven** [comment] 2024-08-19 00:27
want me to load 2.4.10 and check for errors?

**Comment by linuxgruven** [comment] 2024-08-19 00:28
![error2](https://github.com/user-attachments/assets/00c9e413-f423-4482-a407-c8bcd6cf74f1)

**Comment by linuxgruven** [comment] 2024-08-19 00:29
aw my vscode is out of date...thought snap handled that...

**Comment by linuxgruven** [comment] 2024-08-19 00:30
I dont think there is a newer version ready for me

**Comment by ayecue** [comment] 2024-08-19 00:31
How does it show hover tooltips etc if the extension is unable to get activated 😅

**Comment by linuxgruven** [comment] 2024-08-19 00:33
that is with 2.4.10 no hover or go to...

**Comment by linuxgruven** [comment] 2024-08-19 00:34
the first error was with 2.4.8 second error is with 2.4.10

**Comment by linuxgruven** [comment] 2024-08-19 00:34
2.4.8. everything works

**Comment by linuxgruven** [comment] 2024-08-19 00:39
so using the latest flatpack version of vscode 2.4.10 is working

**Comment by linuxgruven** [comment] 2024-08-19 00:42
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.3-1-MANJARO

**Comment by linuxgruven** [comment] 2024-08-19 00:44
![works](https://github.com/user-attachments/assets/340e4e4b-3f58-4b79-94d0-71d2a394e920)

**Comment by ayecue** [comment] 2024-08-19 00:44
Tested it with manjaro linux in a VM seems to work fine. VSCode version is 1.92.2 as well.

**Comment by ayecue** [comment] 2024-08-19 00:45
Nice so then it's resolved for you?

**Comment by linuxgruven** [comment] 2024-08-19 00:45
yes thank you

**Comment by ayecue** [comment] 2024-08-19 00:46
No worries. Thanks for checking with the latest version. Good to know for the future as well.

Closing the issue then.

**Closed by ayecue** 2024-08-19 00:46 UTC
